### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by KBObsidienne** [microsoft/Odyss-e-de-Teams#9]
Hello,
We can't find some of the files mentioned in the ReadMe document. These are the following files:
- t_question.csv
- t_response.csv
- Q&A_EN.xlsx
- The Teams Odyssey - Game Master Guide.pdf

Could you add them? Or if they are present, please specify in which folder?

Thank you in advance,
Sincerely

**Comment by Tinathnath** [comment]
Hi,
In addition, the `data.sql` script calls `public.i_process_backlog_question();` function wich references a file that is also missing, and is a unix path so I guess it won't work on Windows :(
```sql
COPY public.i_question FROM '/var/lib/postgresql/data/backlog_question.csv' DELIMITER ';' CSV HEADER;
```

**Comment by jjabewe** [comment]
Hello, 
As KBObsidienne, I am blocked to import CSV files, because it doesn't exist.
And the other files too.
It's just a little problematic. :p 
They are not in the folders. Could you add them, please ?
Thank you in advance,

**Comment by rharbeg2** [comment]
Any feedback on this? Facing the same issue

**Comment by matthieugi** [comment]
Hi everyone,

Thank you very much for your interest in Teams Odysee. I am working internally to bring missing questions and answers files to the repository.  

I will bring communication assets as soon as possible in english, but for now french assets for Q&A and master guide are accessible in [PACKAGE_ODYSSEE_FR](https://github.com/microsoft/Odyss-e-de-Teams/tree/main/PACKAGE_ODYSSEE_FR) folder.

**Comment by rharbeg2** [comment]
@matthieugi  thank you for getting back to us. 

The issue is not really FR or EN but missing files altogther. As you can see in the documentation provided ([Readme](https://github.com/microsoft/Odyss-e-de-Teams/blob/main/README_en.md)) step 29, we have to use t_question.csv and t_response.csv but these files are absent from all files. 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/101880466/159234520-74231e47-2f66-4d07-b8c8-091ac9d8ea99.png">

Unless you show us how to use the file here "PACKAGE_ODYSSEE_FR/Q&A_FR.xlsx " and make it t_questions.csv and t_response.csv
thanks

**Comment by matthieugi** [comment]
I just added the missing files to the repo.

t_question.csv & t_response.csv are available [in the postgres folder](https://github.com/microsoft/Odyss-e-de-Teams/tree/main/postgres)

Q&A_EN.xlsx & Game Master Guide.pdf are available to the english communication assets [folder](https://github.com/microsoft/Odyss-e-de-Teams/tree/main/PACKAGE_ODYSSEY_EN)

@Tinathnath we have removed the old dependencies to i_question table and the associated unix link.

**Comment by Tinathnath** [comment]
Thanks ! I'll try that :)
